### ISSUE TITLE
"NoClassDefFoundError: org/apache/commons/lang/StringUtils" error when building BinNavi

### ISSUE THREAD

**Issue by afiskon** [google/binnavi#23]
```
eax@fujitsu:~/temp/binnavi$ mvn dependency:copy-dependencies
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building binnavi 6.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: file:///home/eax/temp/binnavi/lib/xml-apis/xml-apis/2.0.2/xml-apis-2.0.2.pom
Exception in thread "pool-1-thread-1" ---------------------------------------------------
constituent[0]: file:/usr/share/maven/lib/aether-connector-wagon.jar
constituent[1]: file:/usr/share/maven/lib/plexus-component-annotations.jar
constituent[2]: file:/usr/share/maven/lib/maven-aether-provider-3.x.jar
constituent[3]: file:/usr/share/maven/lib/plexus-interpolation.jar
constituent[4]: file:/usr/share/maven/lib/plexus-sec-dispatcher.jar
constituent[5]: file:/usr/share/maven/lib/aether-spi.jar
constituent[6]: file:/usr/share/maven/lib/maven-core-3.x.jar
constituent[7]: file:/usr/share/maven/lib/plexus-cipher.jar
constituent[8]: file:/usr/share/maven/lib/maven-artifact-3.x.jar
constituent[9]: file:/usr/share/maven/lib/plexus-utils.jar
constituent[10]: file:/usr/share/maven/lib/commons-cli.jar
constituent[11]: file:/usr/share/maven/lib/wagon-file.jar
constituent[12]: file:/usr/share/maven/lib/commons-httpclient.jar
constituent[13]: file:/usr/share/maven/lib/maven-model-3.x.jar
constituent[14]: file:/usr/share/maven/lib/maven-repository-metadata-3.x.jar
constituent[15]: file:/usr/share/maven/lib/maven-plugin-api-3.x.jar
constituent[16]: file:/usr/share/maven/lib/maven-compat-3.x.jar
constituent[17]: file:/usr/share/maven/lib/wagon-provider-api.jar
constituent[18]: file:/usr/share/maven/lib/aether-api.jar
constituent[19]: file:/usr/share/maven/lib/maven-settings-builder-3.x.jarjava.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils

constituent[20]: file:/usr/share/maven/lib/wagon-http-shaded.jar
	at org.apache.maven.wagon.providers.file.FileWagon.resolveDestinationPath(FileWagon.java:206)
	at org.apache.maven.wagon.providers.file.FileWagon.resourceExists(FileWagon.java:265)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:577)
	at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
constituent[21]: file:/usr/share/maven/lib/maven-model-builder-3.x.jar
constituent[22]: file:/usr/share/maven/lib/aether-util.jar
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.StringUtilsconstituent[23]: file:/usr/share/maven/lib/sisu-guice.jar

	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
constituent[24]: file:/usr/share/maven/lib/sisu-inject-plexus.jar	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)

constituent[25]: file:/usr/share/maven/lib/commons-codec.jar	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)

	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
constituent[26]: file:/usr/share/maven/lib/aether-impl.jar	... 7 more

constituent[27]: file:/usr/share/maven/lib/maven-settings-3.x.jar
constituent[28]: file:/usr/share/maven/lib/maven-embedder-3.x.jar
constituent[29]: file:/usr/share/maven/lib/commons-logging.jar
constituent[30]: file:/usr/share/maven/lib/guava.jar
constituent[31]: file:/usr/share/maven/lib/sisu-inject-bean.jar
---------------------------------------------------
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
	at org.apache.maven.wagon.providers.file.FileWagon.resolveDestinationPath(FileWagon.java:206)
	at org.apache.maven.wagon.providers.file.FileWagon.resourceExists(FileWagon.java:265)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:577)
	at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.StringUtils
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
	... 7 more
```

```
eax@fujitsu:~/temp/binnavi$ java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

eax@fujitsu:~/temp/binnavi$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
```

**Comment by afiskon** [comment]
```
eax@fujitsu:~/temp/binnavi$ mvn --version
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-62-generic", arch: "amd64", family: "unix"
```

**Comment by afiskon** [comment]
Sorry, it appears to be not a binnavi related problem. After updating maven using this PPA https://launchpad.net/~andrei-pozolotin/+archive/ubuntu/maven3 everything works as expected.

**Comment by cblichmann** [comment]
No worries :)
A good indicator of whether it's an issue you're having locally or with BinNavi itself is the Travis CI build status indicator on the project page - if green, everything's fine :P
