### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by Hacksign** [google/binnavi#5]
execute of binnavi with error.
jdk version not fit:
>> java -jar binnavi-all.jar 
Starting BinNavi 6.0.0 Build: <unknown>/<unknown>
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/security/zynamics/binnavi/yfileswrap/Gui/MainWindow/ProjectTree/Nodes/Root/Component/CRootNodeComponent : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.google.security.zynamics.binnavi.Gui.MainWindow.ProjectTree.Nodes.Root.CRootNode.<init>(CRootNode.java:58)
	at com.google.security.zynamics.binnavi.Gui.MainWindow.ProjectTree.CProjectTree.<init>(CProjectTree.java:94)
	at com.google.security.zynamics.binnavi.Gui.MainWindow.CProjectMainPanel.<init>(CProjectMainPanel.java:87)
	at com.google.security.zynamics.binnavi.Gui.MainWindow.CProjectMainFrame.<init>(CProjectMainFrame.java:69)
	at com.google.security.zynamics.binnavi.CMain.main(CMain.java:122)

**Comment by cblichmann** [comment]
You need to run it with a Java 8 JRE, see http://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0.

**Comment by schacker** [comment]
yes, right!

**Comment by useretail** [comment]
@cblichmann any soloution for openjdk?

**Comment by thomasdullien** [comment]
@useretail: Does openjdk-8-jre or openjdk-9-jre not work ?
