### ISSUE TITLE
Failed to load monoreil sample plugin 

### ISSUE THREAD

**Issue by ghost** [google/binnavi#87]
Hi, 

whenever i tried to load monoreil sample plugin, i got failure with below console output.

```
Reason: java.lang.VerifyError: java.lang.VerifyError: (class: org/python/proxies/__builtin__$SkeletonLatticeElement$3, method: super__equals signature: (Lcom/google/security/zynamics/reil/algorithms/mono/interfaces/ILatticeElementMono1;)Z) Illegal use of nonvirtual function call in <script> at line number 53
```

Could you please let me know how to solve this problem? 
Thank you. 

J.H. Jeong 
- Environment
  - Binnavi version : 6.01 
  - OS : MAC OS X 10.11.2

**Comment by thomasdullien** [comment]
Hey there,

I'll have to look into this (which may take a few days), but my gut feeling
says it may have something to do
with the obfuscation of the yfiles part ...

Sorry for the likely delay.

Cheers,
Thomas

2016-04-04 7:52 GMT+08:00 Jeong, JiHoon <notifications@github.com>:

**Comment by binoopang** [comment]
Thank you for your response. 

I have one more thing. In your cansecwest2009 slide(page 49), you mentioned some of monoreil example such as `register tracking` and `negative array indexing`.
I could find `register tracking` example in the script directory but I couldn't find `negative array indexing`.
Could you release this example so that I can refer to them? 

Thank you for your help.

J.H. Jeong

**Comment by gitttt** [comment]
@thomasdullien :
I am also interested in the "negative array indexing" example. Any news on this?

@binoopang: 
Does the bug also exist in the latest official release (6.1) ?

**Comment by thomasdullien** [comment]
Hey there,

regarding the "negative array indexing" example: I think we will safely
have to assume it has been
lost to the ages. Honestly, I think this may be for the better.

It may be a good idea to try to build a proper memory domain into BinNavi
(e.g. something that manages
contents of memory cells) in the near future...

Cheers,
Thomas

2016-05-24 9:26 GMT+02:00 gitttt <notifications@github.com>:

**Comment by gitttt** [comment]
Hi!
I am having a similar (the same?) error when trying to start the mono reil sample.
I removed as much code as possible to narrow down the error. This code still causes it:

```
class SkeletonLatticeElement(ILatticeElement):
	def __init__(self):
		self.written_registers = Set()

	def equals(self, rhs):
		pass
```
If I rename the "equals", e.g. to "equal", then the error is gone.

Here the stack trace (the cmd output) of the error:
```
D:\jython2.7.0\bin>jython.exe d:\temp\sample.py
Traceback (most recent call last):
  File "d:\temp\sample.py", line 48, in <module>
    class SkeletonLatticeElement(ILatticeElement):
java.lang.VerifyError: (class: org/python/proxies/__main__$SkeletonLatticeElemen
t$0, method: super__equals signature: (Lcom/google/security/zynamics/reil/algori
thms/mono/interfaces/ILatticeElementMono1;)Z) Illegal use of nonvirtual function
 call
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetPublicMethods(Unknown Source)
        at java.lang.Class.getMethods(Unknown Source)
        at org.python.core.PyJavaType.init(PyJavaType.java:284)
        at org.python.core.PyType.createType(PyType.java:1412)
        at org.python.core.PyType.addFromClass(PyType.java:1348)
        at org.python.core.PyType.fromClass(PyType.java:1439)
        at org.python.core.PyType.setupProxy(PyType.java:685)
        at org.python.core.PyType.newType(PyType.java:212)
        at org.python.core.PyType.type___new__(PyType.java:152)
        at org.python.core.PyType$exposed___new__.new_impl(Unknown Source)
        at org.python.core.PyType.invokeNew(PyType.java:494)
        at org.python.core.PyType.type___call__(PyType.java:1706)
        at org.python.core.PyType.__call__(PyType.java:1696)
        at org.python.core.PyObject.__call__(PyObject.java:496)
        at org.python.core.Py.makeClass(Py.java:1878)
        at org.python.core.Py.makeClass(Py.java:1839)
        at org.python.core.Py.makeClass(Py.java:1831)
        at org.python.pycode._pyx0.f$0(d:\temp\sample.py:107)
        at org.python.pycode._pyx0.call_function(d:\temp\sample.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyCode.call(PyCode.java:18)
        at org.python.core.Py.runCode(Py.java:1386)
        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296
)
        at org.python.util.jython.run(jython.java:362)
        at org.python.util.jython.main(jython.java:142)

java.lang.VerifyError: java.lang.VerifyError: (class: org/python/proxies/__main_
_$SkeletonLatticeElement$0, method: super__equals signature: (Lcom/google/securi
ty/zynamics/reil/algorithms/mono/interfaces/ILatticeElementMono1;)Z) Illegal use
 of nonvirtual function call
```

**Comment by thomasdullien** [comment]
Hey there,

I won't be able to look into this until next Friday :-/ sorry for that.
Will check it then!

2016-10-15 20:54 GMT+02:00 gitttt <notifications@github.com>:

**Comment by cblichmann** [comment]
The BinNavi project is no longer under active development.
