### ISSUE TITLE
Register Tracking / MonoREIL(?) broken

### ISSUE THREAD

**Issue by gitttt** [google/binnavi#91]
- OS: Ubuntu 14.04-04 32bit
- java version "1.8.0_92"
- Target binary: /bin/ls
- Binnavi version: Github release BinNavi 6.1 with BinExport 9

Tracking registers, no matter which (native or REIL), has no visible effect. Once I click on "track operand forward" the terminal says:

> Starting BinNavi 6.1 @ 06f0c04
May 24, 2016 8:40:04 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <1>    <7 ms>    SELECT relname FROM pg_class WHERE relname = 'modules'
May 24, 2016 8:40:04 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <2>    <2 ms>    SELECT attname FROM pg_attribute WHERE attrelid =  (SELECT oid FROM pg_class WHERE relname = 'modules') AND attname = 'version';
May 24, 2016 8:40:04 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <3>    <1 ms>    SELECT relname FROM pg_class WHERE relname = 'bn_sections'
May 24, 2016 8:40:04 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <4>    <0 ms>    SELECT pg_backend_pid() AS pid
May 24, 2016 8:40:04 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <5>    <1 ms>    SELECT relname FROM pg_class WHERE relname = 'bn_sections'
May 24, 2016 8:40:04 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <6>    <2 ms>    SELECT user_id, user_name FROM bn_users
May 24, 2016 8:40:04 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <7>    <1 ms>    SELECT user_id, user_name FROM bn_users
May 24, 2016 8:40:04 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <8>    <4 ms>    SELECT relname FROM pg_class WHERE relname = 'bn_tags'
May 24, 2016 8:40:04 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <9>    <2 ms>    select id, parent_id, name, description from bn_tags where type = 'view_tag'
May 24, 2016 8:40:04 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <1>    <27 ms>    LISTEN view_changes
May 24, 2016 8:40:04 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <10>    <1 ms>    SELECT relname FROM pg_class WHERE relname = 'bn_tags'
May 24, 2016 8:40:04 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <2>    <1 ms>    LISTEN section_changes
May 24, 2016 8:40:04 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <3>    <0 ms>    LISTEN function_changes
May 24, 2016 8:40:04 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <4>    <1 ms>    LISTEN type_instances_changes
May 24, 2016 8:40:04 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <5>    <1 ms>    LISTEN comment_changes
May 24, 2016 8:40:04 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <6>    <1 ms>    LISTEN types_changes
May 24, 2016 8:40:04 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <11>    <91 ms>    select id, parent_id, name, description from bn_tags where type = 'node_tag'
May 24, 2016 8:40:04 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <12>    <0 ms>    SELECT * FROM bn_debuggers
May 24, 2016 8:40:04 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <13>    <2 ms>    SELECT relname FROM pg_class WHERE relname = 'bn_projects'
May 24, 2016 8:40:04 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <14>    <1 ms>    SELECT id, name, description, creation_date, modification_date,  (SELECT count(*) FROM bn_address_spaces WHERE project_id = bn_projects.id)  AS addressspace_count FROM bn_projects
May 24, 2016 8:40:04 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <15>    <1 ms>    SELECT relname FROM pg_class WHERE relname = 'modules'
May 24, 2016 8:40:04 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <16>    <8 ms>    SELECT id, name FROM modules ORDER BY id
May 24, 2016 8:40:05 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <17>    <5 ms>    SELECT table_name FROM information_schema.tables  WHERE table_catalog = 'new_database' 
May 24, 2016 8:40:05 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <18>    <2 ms>    SELECT count(*) AS fcount  FROM ex_1_functions  WHERE address <> 0  OR type <> 3
May 24, 2016 8:40:05 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <19>    <3 ms>    SELECT relname FROM pg_class WHERE relname = 'bn_modules'
May 24, 2016 8:40:05 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <20>    <3 ms>    SELECT id, raw_module_id, bn_modules.name,  md5, sha1, description, import_time, modification_date, file_base, image_base, stared,  initialization_state, debugger_id,  (SELECT count(*) FROM bn_functions  WHERE id = bn_functions.module_id)  AS function_count,  (SELECT count(*) FROM bn_module_views JOIN bn_views ON view_id = id  WHERE type = 'non-native' and module_id = bn_modules.id)  AS view_count FROM bn_modules  WHERE raw_module_id IS NOT NULL ORDER BY id
May 24, 2016 8:40:08 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <21>    <1 ms>    SELECT bn_tagged_views.view_id, tag_id FROM bn_tagged_views JOIN bn_module_views ON bn_module_views.view_id = bn_tagged_views.view_id WHERE module_id = 1 ORDER BY view_id
May 24, 2016 8:40:08 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <22>    <1 ms>    SELECT bn_tagged_views.view_id, tag_id FROM bn_tagged_views JOIN bn_module_views ON bn_module_views.view_id = bn_tagged_views.view_id WHERE module_id = 1 ORDER BY view_id
May 24, 2016 8:40:08 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <23>    <1 ms>    SELECT bn_tagged_views.view_id, tag_id FROM bn_tagged_views JOIN bn_module_views ON bn_module_views.view_id = bn_tagged_views.view_id WHERE module_id = 1 ORDER BY view_id
May 24, 2016 8:40:09 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <24>    <23 ms>    SELECT bn_tagged_views.view_id, tag_id FROM bn_tagged_views JOIN bn_module_views ON bn_module_views.view_id = bn_tagged_views.view_id WHERE module_id = 1 ORDER BY view_id
May 24, 2016 8:40:09 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <25>    <0 ms>    SELECT bn_tagged_views.view_id, tag_id FROM bn_tagged_views JOIN bn_module_views ON bn_module_views.view_id = bn_tagged_views.view_id WHERE module_id = 1 ORDER BY view_id
May 24, 2016 8:40:09 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <26>    <1 ms>    SELECT view_id, function FROM bn_function_views WHERE module_id = 1
May 24, 2016 8:40:09 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <27>    <1 ms>    SELECT nodes.id, function FROM bn_nodes AS nodes JOIN bn_function_nodes AS function_nodes ON nodes.id = function_nodes.node_id WHERE nodes.view_id = 405
May 24, 2016 8:40:09 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <28>    <4 ms>    SELECT source_node_id, target_node_id FROM bn_nodes JOIN bn_edges ON bn_nodes.id = bn_edges.source_node_id WHERE view_id = 405
May 24, 2016 8:40:09 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <29>    <23 ms>    select id, name, description from bn_traces join bn_module_traces on bn_module_traces.trace_id = bn_traces.id where bn_module_traces.module_id = 1
May 24, 2016 8:40:40 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <30>    <1 ms>    SELECT id, comment_id , collapsed, x, y, width, height, color, selected, visible  FROM bn_nodes JOIN bn_group_nodes ON id = node_id WHERE view_id = 126
May 24, 2016 8:40:40 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <31>    <0 ms>    SELECT id, parent_id FROM bn_nodes WHERE view_id = 126 ORDER BY id
May 24, 2016 8:40:40 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <32>    <0 ms>    SELECT node_id, tag_id FROM bn_tagged_nodes WHERE node_id IN (577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594)
May 24, 2016 8:40:40 PM com.google.security.zynamics.binnavi.Log.NaviLogger info
INFO: <33>    <55 ms>    SELECT e.id, gc.comment_id FROM bn_global_edge_comments AS gc  join bn_instructions AS src_inst on gc.src_address = src_inst.address AND gc.src_module_id = src_inst.module_id  join bn_instructions AS dst_inst on gc.dst_address = dst_inst.address AND gc.dst_module_id = dst_inst.module_id  join bn_codenode_instructions AS src_nodes on src_nodes.address = gc.src_address AND src_nodes.position = 0 AND src_nodes.module_id = gc.src_module_id  join bn_codenode_instructions AS dst_nodes on dst_nodes.address = gc.dst_address AND dst_nodes.position = 0 AND dst_nodes.module_id = gc.dst_module_id  join bn_edges AS e ON e.source_node_id = src_nodes.node_id AND e.target_node_id = dst_nodes.node_id  join bn_nodes AS src_n ON e.source_node_id = src_n.id  join bn_nodes AS dst_n ON e.target_node_id = dst_n.id  WHERE src_n.view_id = 126 AND dst_n.view_id = 126
Exception in thread "AWT-EventQueue-0" java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy0.actionPerformed(Unknown Source)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.security.zynamics.binnavi.Gui.Actions.CActionProxy.invoke(CActionProxy.java:80)
	... 39 more
Caused by: java.lang.AbstractMethodError: com.google.security.zynamics.reil.yfileswrap.algorithms.mono2.common.instructiongraph.CReilInstructionGraph.size()I
	at com.google.security.zynamics.reil.algorithms.mono2.common.MonoReilSolver.<init>(MonoReilSolver.java:76)
	at com.google.security.zynamics.reil.algorithms.mono2.registertracking.RegisterTracker.track(RegisterTracker.java:62)
	at com.google.security.zynamics.binnavi.Gui.GraphWindows.BottomPanel.RegisterTracker.CTracking.track(CTracking.java:66)
	at com.google.security.zynamics.binnavi.Gui.GraphWindows.BottomPanel.RegisterTracker.CTrackOperandAction.actionPerformed(CTrackOperandAction.java:88)
	... 44 more

**Comment by thomasdullien** [comment]
Hey there,

I should be able to look into this tomorrow or Saturday :-)

Cheers,
Thomas

2016-05-24 23:15 GMT+02:00 gitttt <notifications@github.com>:

**Comment by gitttt** [comment]
Excellent. Thanks a lot!

**Comment by thomasdullien** [comment]
Hey all,

ok, so I dug into this. The root of the issue is the following:
https://github.com/google/binnavi/issues/65

In the commit fixing the issue, a version-number suffix is introduced to the yfileswrap-obfuscated.jar, but the build.xml is not adapted in turn - leading to "ant build-binnavi-fat-jar" still using the old / outdated version of yfileswrap-obfuscated.jar (instead the yfileswrap-obfuscated-6.?.jar).

I have fixed this locally in my git right now by doing the following three steps:

(1) Change the build.xml to reflect the version number
diff --git a/build.xml b/build.xml
index 67fb00a..266ca63 100644
--- a/build.xml
+++ b/build.xml
@@ -41,7 +41,7 @@
   </path>
   <path id="yfileswrap.class.path">
     <fileset id="yfileswrap.jar" dir="${zynamics.dir}/lib/">
-      <include name="yfileswrap-obfuscated.jar"/>
+      <include name="yfileswrap-obfuscated-6.1.jar"/>
     </fileset>
   </path>
   <path id="zylib.class.path">

(2) Copying yfileswrap-obfuscated-6.1.jar to 
src/main/java/com/google/security/zynamics/lib/yfileswrap-obfuscated-6.1.jar

(3) Rebuilding using "ant build-binnavi-fat-jar"

This is only a temporary fix, will look into the "proper" fix now.

**Comment by gitttt** [comment]
@thomasdullien Thank you for the fix and thank you for having taken a look at it - on a Saturday morning :-)

**Comment by cblichmann** [comment]
Arrgs, sorry. I should've tested this more thoroughly. Seems I forgot to "git add" the build.xml. I'll properly rebuild it when I'm in the office.

**Comment by cblichmann** [comment]
71789b3 finally fixes the issue.
